import { StyleSheet } from 'react-native';

const ResultStyle = StyleSheet.create({
  container: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  topinfo: {
    backgroundColor: "#EDD790",
    borderRadius: 30,
    width: '100%',
    height: '65%',
    display: "flex",
    alignItems: "center",
  },
  info: {
    marginTop: 50,
    width: 375,
    height: '25%',
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  backmenu: {
    marginLeft: 20,
    width: 55,
    height: 55,
    display: "flex",
    flexDirection: "column",
  },
  infos: {
    marginLeft: 575,
    width: 375,
    height: 55,
    display: "flex",
    flexDirection: "row",
  },
  rectangleA: {
    width: 55,
    height: 55,
    backgroundColor: "#6ea9f7",
    padding: 5,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  mainphoto: {
    width: 300,
    height: 300,
  },
  content: {
    width: 300,
    height: 300,
  },
  elipse2: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    boxSizing: "border-box",
    display: "flex",
    width: 300,
    height: 300,
    borderRadius: 100,
    borderWidth: 3,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  elipse: {
    flexDirection: "column",
    justifyContent: "center",
    display: "flex",
    alignItems: "center",
    width: 275,
    height: 275,
    borderRadius: 100,
    backgroundColor: "#FFFFFF",
  },
  img: {
    width: 250,
    height: 250,
    borderRadius: 100,
  },
  bottominfo: {
    backgroundColor: '#FFFFFF',
    width: '100%',
    height: 322,
    borderRadius: 30,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  circleChart: {
    width: 200,
    height: 200,
  },
  circleChartPercentage: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 200,
    height: 200,
    transform: [{ rotate: "-90deg" }]
  },
  contents: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: 175,
    height: 175,
    borderRadius: 100,
    transform: [ { rotate: "90deg" }],
  },
  scanningText: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 27,
    lineHeight: 32,
    color: '#000',
  },
  resultText: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 28,
    lineHeight: 32,
    color: '#000',
  },
});

export default ResultStyle;
