import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const ResultFoodStyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  centerContainer: {
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  info: {
    marginTop: 50,
    width: 375,
    height: 75,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  userGreeting: {
    padding: 10,
  },
  userGreetingText: {
    fontSize: 14,
    color: "#4B5563",
    lineHeight: 20,
    textAlign: "center",
  },
  highlightText: {
    fontWeight: "700",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#6B7280",
    textAlign: "center",
  },
  errorText: {
    fontSize: 16,
    color: "#EF4444",
    textAlign: "center",
    marginBottom: 20,
  },
  actionButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
  },
  actionButtonText: {
    color: "white",
    fontWeight: "600",
    fontSize: 16,
  },
  scrollContent: {
    flex: 1,
  },
  mainFoodCard: {
    backgroundColor: "white",
    borderRadius: 12,
    margin: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    overflow: "hidden",
  },
  mainFoodImage: {
    width: "100%",
    height: 200,
    backgroundColor: "#E5E7EB",
  },
  mainFoodDetails: {
    padding: 16,
  },
  foodTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  mainFoodName: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1F2937",
    flex: 1,
  },
  foodType: {
    fontSize: 14,
    color: "#6B7280",
    marginBottom: 16,
  },
  ratingContainer: {
    marginTop: 24,
    marginBottom: 8,
  },
  ratingLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: "#4B5563",
    marginBottom: 8,
  },
  starContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  starIcon: {
    marginRight: 8,
  },
  ratedContainer: {
    marginTop: 8,
    backgroundColor: "#F3F4F6",
    padding: 12,
    borderRadius: 8,
  },
  ratedText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#4B5563",
    textAlign: "center",
  },
  suggestionsSection: {
    padding: 16,
    backgroundColor: "white",
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1F2937",
    marginBottom: 16,
  },
  suggestionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  suggestionCard: {
    width: "48%",
    marginBottom: 16,
    borderRadius: 8,
    backgroundColor: "white",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  suggestionImage: {
    width: "100%",
    height: 100,
    backgroundColor: "#F3F4F6",
  },
  suggestionDetails: {
    padding: 10,
  },
  suggestionName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1F2937",
    marginBottom: 4,
  },
  suggestionType: {
    fontSize: 12,
    color: "#6B7280",
  },
  nutritionSection: {
    padding: 16,
    backgroundColor: "white",
    marginHorizontal: 16,
    marginBottom: 24,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  nutrientsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  nutrientItem: {
    width: "48%",
    padding: 12,
    marginBottom: 12,
    backgroundColor: "#F9FAFB",
    borderRadius: 8,
  },
  nutrientItemPriority: {
    backgroundColor: "#F0F9FF", 
    borderWidth: 1,
    borderColor: "#BFDBFE",
  },
  nutrientName: {
    fontSize: 12,
    fontWeight: "500",
    color: "#4B5563",
    marginBottom: 4,
  },
  nutrientValue: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1F2937",
  },
  nutrientUnit: {
    fontSize: 12,
    color: "#6B7280",
  },
  priorityLabel: {
    fontSize: 10,
    color: "#3B82F6",
    fontWeight: "500",
    marginTop: 4,
  },
  footer: {
    flexDirection: "row",
    padding: 16,
    backgroundColor: "white",
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  footerButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    marginHorizontal: 4,
    borderRadius: 8,
  },
  footerButtonText: {
    marginLeft: 8,
    fontSize: 16,
    fontWeight: "500",
    color: "#374151",
  },
  footerSaveButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    marginHorizontal: 4,
    borderRadius: 8,
  },
  priorityNutrientSection: {
    marginTop: 8,
    padding: 12,
    backgroundColor: "#F0F9FF",
    borderRadius: 8,
    marginBottom: 16,
  },
  priorityNutrientTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#3B82F6",
    marginBottom: 8,
  },
  priorityNutrientDescription: {
    fontSize: 13,
    color: "#4B5563",
    lineHeight: 18,
  },
  // New styles for the explanation section
  explanationSection: {
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    marginBottom: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#6EA9F7", // Will be dynamically colored based on emotion
  },
  explanationTitle: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 16,
    marginBottom: 8,
    color: "#1F2937",
  },
  explanationText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    lineHeight: 20,
    color: "#4B5563",
  },
  scientificSummary: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    lineHeight: 20,
    fontStyle: "italic",
    color: "#4B5563",
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  // New styles for priority nutrients list
  priorityNutrientsContainer: {
    marginTop: 16,
    marginBottom: 16,
  },
  priorityNutrientItem: {
    backgroundColor: "#F0F9FF",
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#BFDBFE",
  },
  priorityNutrientHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  priorityNutrientName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1F2937",
  },
  priorityNutrientValue: {
    fontSize: 12,
    color: "#4B5563",
    marginBottom: 4,
  },
  priorityNutrientShortDesc: {
    fontSize: 12,
    color: "#4B5563",
    lineHeight: 16,
  },
  // Modal styles for detailed nutrient view
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    width: width * 0.9,
    backgroundColor: "white",
    borderRadius: 12,
    overflow: "hidden",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
    padding: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1F2937",
  },
  modalCloseButton: {
    padding: 4,
  },
  modalCloseText: {
    fontSize: 14,
    color: "#6B7280",
  },
  modalBody: {
    padding: 16,
  },
  modalNutrientName: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1F2937",
    marginBottom: 4,
  },
  modalNutrientValue: {
    fontSize: 14,
    color: "#4B5563",
    marginBottom: 16,
  },
  modalDivider: {
    height: 1,
    backgroundColor: "#E5E7EB",
    marginVertical: 16,
  },
  modalSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1F2937",
    marginBottom: 8,
  },
  modalExplanation: {
    fontSize: 14,
    color: "#4B5563",
    lineHeight: 20,
  },
  modalResearch: {
    fontSize: 14,
    color: "#4B5563",
    lineHeight: 20,
    fontStyle: "italic",
  },
  mainFoodImageContainer: {
    position: 'relative',
    width: '100%',
    height: 200,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    overflow: 'hidden',
  },
  imageLoadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default ResultFoodStyle;